branch-defaults:
  master:
    environment: MASTER-teachie-awards
    group_suffix: null
deploy:
  artifact: teachie-awards-0.0.1-SNAPSHOT.jar
global:
  application_name: teachie-awards
  branch: null
  default_ec2_keyname: null
  default_platform: Java 8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application