branch-defaults:
  master:
    environment: TeachieAwardsVpc-env
    group_suffix: null
deploy:
  artifact: target/teachie-awards-0.0.1-SNAPSHOT.jar
environment-defaults:
  TeachieAwardsVpc-env:
    branch: null
    repository: null
global:
  application_name: teachie-awards-vpc
  branch: null
  default_ec2_keyname: null
  default_platform: Java 8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
